name = "telegram-rss-bot"
main = "src/index.js"
compatibility_date = "2024-01-15"

# KV存储绑定
[[kv_namespaces]]
binding = "RSS_CACHE"
id = "f7de55d4e0d7496b87801f71fe785e98"

# D1数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "telegram-rss-db"
database_id = "e9b66573-74b1-4464-a73b-635aaa19736e"

# 定时任务 - 每10分钟检查RSS
[triggers]
crons = ["*/2 * * * *"]

# 生产环境配置
[env.production]
name = "telegram-rss-bot-prod"

[[env.production.kv_namespaces]]
binding = "RSS_CACHE"
id = "f7de55d4e0d7496b87801f71fe785e98"

[[env.production.d1_databases]]
binding = "DB"
database_name = "telegram-rss-db-prod"
database_id = "e9b66573-74b1-4464-a73b-635aaa19736e"
